[package]
name = "easy-cut"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "easy_cut_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri-plugin-opener = "2"
tauri = { version = "2", features = ["protocol-asset"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# 引入 tokio 运行时，用于构建高吞吐量的异步视频处理队列
tokio = { version = "1", features = ["full"] }
tauri-plugin-dialog = "2"
# 用于执行本地系统命令 (调用 FFmpeg)
sha2 = "0.10"  # <--- 新增：用于生成极速视频指纹
dirs = "5" # <--- 新增：用于精准获取操作系统的Documents/Home目录
open = "5"
# 🌟 新增：用于获取底层硬件机器码的权威库
machine-uid = "0.3.0"
# 🌟 新增：RSA 非对称加密与哈希算法
rsa = {version = "0.9.3" ,features = ["sha2", "pem"] }
# 🌟 新增：用于编解码激活串
base64 = "0.21.5"

# 🌟 新增：强大的异步生态与流式并发控制
futures = "0.3.28"
